### ISSUE TITLE
Standardize entity handling across datasets

### ISSUE THREAD

**Issue by Tiyop** [dataforgoodfr/batch7_beges#11]
User should be able to:
- Switch between orgs/services in a same view (via filter panel)
- Select multiple orgs/services

There should be mapping between chorus/osfi/odrive for orgs and services so 1) transition between views is smooth for the user, 2) an overview dashboard (with all datasets) can be developped.

**Comment by antoan2** [comment]
@Tiyop you should check this PR before working on this :s
https://github.com/dataforgoodfr/batch7_beges/pull/15

**Comment by antoan2** [comment]
@Tiyop do you think this is solved with https://github.com/dataforgoodfr/batch7_beges/pull/15 ?
